[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
remappings = [
    "solady=lib/solady/src",
    "sablier/v2-core=lib/v2-core",
    "sablier/v2-periphery=lib/v2-periphery",
    "@prb/math/=lib/prb-math/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
